language: generic

services:
  - docker

after_succes:
  - docker build -t amanoyaku/user-wishlist-app .

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push amanoyaku/user-wishlist-app

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: my-user-wishlist-app
  env: Myuserwishlistapp-env
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket_name: "multi-container-wishlist-app"
  bucket_path: "docker"
  on:
    branch: main